// Descriptions from Fred Parker's site (http://www.fredparker.com/ultexp1.htm)
export const levels = {
    "-6": "Night, subject under starlight only.",
    "-5": "Night, subject under crescent moon.",
    "-4": "Night, subject under half moon.",
    "-3": "Night, subject under full moon.",
    "-2": "Night, snowscape under full moon.",
    "-1": "Subjects lit by dim ambient artificial light. End of Blue Hour",
    "0": "Subjects lit by dim ambient artificial light.",
    "1": "Distant view of lighted skyline.",
    "2": "Lightning (with time exposure). Total eclipse of moon.",
    "3": "Fireworks (with time exposure).",
    "4": "Candle lit close-ups. Christmas lights, floodlit buildings, fountains, and monuments. Subjects under bright street lamps.",
    "5": "Night home interiors, average light. School or church auditoriums. Subjects lit by campfires or bonfires.",
    "6": "Brightly lit home interiors at night. Fairs, amusement parks.",
    "7": "Bottom of rainforest canopy. Brightly lighted nighttime streets. Indoor sports. Stage shows, circuses.",
    "8": "Las Vegas or Times Square at night. Store windows. Campfires, bonfires, gvml;d,zdgr;burning buildings. Ice shows, football, baseball etc. at night. Interiors with bright florescent lights.",
    "9": "Landscapes, city skylines 10 minutes after sunset. Neon lights, spotlighted subjects.",
    "10": "Landscapes and skylines immediately after sunset.",
    "11": "Sunsets. Subjects in deep shade.",
    "12": "Subject in open shade or heavy overcast.",
    "13": "Subjects in cloudy-bright light (no shadows).",
    "14": "Subjects in weak, hazy sun.",
    "15": "Subjects in bright or hazy sun. (Sunny f/16 rule)",
    "16": "Subjects in bright daylight on sand or snow.",
    "17": "Very bright.  Some man made lighting.",
    "22": "Extremely bright. Rarely encountered in nature.",
  };
  

//   EV	Real-World Situation for Proper Exposure
// 1This chart assumes ISO 100.  from Spencer Cox's Article 
export const simpleLevels = {
"-6" :	"Nighttime landscape under quarter moon",
"-5" :	"Aurora borealis of moderate brightness",
"-4" :	"Nighttime landscape under gibbous moon",
"-3" :	"Nighttime landscape under full moon",
"-2" :	"Nighttime snow or beach landscape under full moon",
"-1" :	"End of blue hour",
"0 ":	"Late in blue hour",
"1 ":	"Middle of blue hour",
"2 ":	"Distant cityscape at night",
"3 ":	"Indoor scene lit only by dim window light",
"4 ":	"Floodlit monuments or fountains at night",
"5 ":	"Typical artificial indoor light",
"6 ":	"Bright indoor lighting",
"7 ":	"Fairs and theme parks at night",
"8 ":	"Bright window displays and advertisements at night",
"9 ":	"Nighttime sporting events under bright light",
"10" :	"Moment after sunset on a clear day",
"11" :	"Daylight on a foggy day",
"12" :	"Moment before sunset on a clear day",
"13" :	"Typical subject on a bright, cloudy day",
"14" :	"Typical subject on a day with hazy sunlight",
"15" :	"Full sunlight on a cloudless day, typical subject",
"16" :	"Full sunlight on a cloudless day, bright subject (i.e. the beach)",
"17" :	"Full sunlight on a cloudless day, highly reflective subject (i.e. snow)",
};