// Descriptions from Fred Parker's site (http://www.fredparker.com/ultexp1.htm)
export const levels = {
    "-6": "Night, subject under starlight only.",
    "-5": "Night, subject under crescent moon.",
    "-4": "Night, subject under half moon.",
    "-3": "Night, subject under full moon.",
    "-2": "Night, snowscape under full moon.",
    "-1": "Subjects lit by dim ambient artificial light.",
    "0": "Subjects lit by dim ambient artificial light.",
    "1": "Distant view of lighted skyline.",
    "2": "Lightning (with time exposure). Total eclipse of moon.",
    "3": "Fireworks (with time exposure).",
    "4": "Candle lit close-ups. Christmas lights, floodlit buildings, fountains, and monuments. Subjects under bright street lamps.",
    "5": "Night home interiors, average light. School or church auditoriums. Subjects lit by campfires or bonfires.",
    "6": "Brightly lit home interiors at night. Fairs, amusement parks.",
    "7": "Bottom of rainforest canopy. Brightly lighted nighttime streets. Indoor sports. Stage shows, circuses.",
    "8": "Las Vegas or Times Square at night. Store windows. Campfires, bonfires, burning buildings. Ice shows, football, baseball etc. at night. Interiors with bright florescent lights.",
    "9": "Landscapes, city skylines 10 minutes after sunset. Neon lights, spotlighted subjects.",
    "10": "Landscapes and skylines immediately after sunset.",
    "11": "Sunsets. Subjects in deep shade.",
    "12": "Subject in open shade or heavy overcast.",
    "13": "Subjects in cloudy-bright light (no shadows).",
    "14": "Subjects in weak, hazy sun.",
    "15": "Subjects in bright or hazy sun. (Sunny f/16 rule)",
    "16": "Subjects in bright daylight on sand or snow.",
    "17": "Very bright.  Some man made lighting.",
    "22": "Extremely bright. Rarely encountered in nature.",
  };
  